# Generated by Django 4.2.5 on 2023-10-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('place_image', models.ImageField(upload_to='images')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
